apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chains.controller.name }}
  namespace: {{ .Values.pipelines.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.chains.controller.name }}
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: {{ .Values.spiffe.socketMount }}/{{ .Values.spiffe.socketFile }}
        - name: TUF_ROOT
          value: {{ .Values.chains.tuf.mountPath }}
        volumeMounts:
        - mountPath: {{ .Values.spiffe.socketMount }}
          name: spiffe-workload-api
        - mountPath: {{ .Values.chains.tuf.mountPath }}
          name: tuf
      volumes:
      - emptyDir: {}
        name: tuf
      - csi:
          driver: csi.spiffe.io
          readOnly: true
        name: spiffe-workload-api
