apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: spiffe-inject-pod
  annotations:
    policies.kyverno.io/title: Inject SPIFFE resources into Pods
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/category: Other
    policies.kyverno.io/description: >-
      Inject SPIFFE CSI volume and workload API Environment Variables and Mounts
spec:
  rules:
    - name: check-spiffe-pod-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
              selector:
                matchLabels:
                  devspaces.spiffe.io/inject: "true"
      mutate:
        patchStrategicMerge:
          spec:
            volumes:
              - name: spiffe-workload-api
                csi:
                  driver: "csi.spiffe.io"
                  readOnly: true
            containers:
              - name: "{{request.object.spec.containers[0].name}}"
                env:
                  - name: SPIFFE_ENDPOINT_SOCKET
                    value: /spiffe-workload-api/spire-agent.sock
                volumeMounts:
                  - name: spiffe-workload-api
                    mountPath: /spiffe-workload-api
